import { t as tx } from './i18n'

export type SoonPage = { title: string; phase: 9 | 10; about: string; links?: { to: string; label: string }[] }

/** Menu items whose screen is not built yet: each opens a "coming soon" page (with the phase and what to use meanwhile). */
export const SOON: Record<string, SoonPage> = {
  '/farmers/deleted': { title: tx('মুছে ফেলা কৃষক'), phase: 9, about: tx('মুছে ফেলা কৃষকের তালিকা, কারণ ও পুনরুদ্ধার।'), links: [{ to: '/farmers', label: tx('কৃষক তালিকা') }] },
  '/lands/owners': { title: tx('মালিক ও চাষি'), phase: 9, about: tx('সব জমির বর্তমান মালিক ও চাষির আলাদা তালিকা।'), links: [{ to: '/lands', label: tx('জমির তালিকা') }] },
  '/lands/borga': { title: tx('বর্গা চাষ'), phase: 9, about: tx('চলমান ও শেষ হওয়া বর্গার তালিকা, মেয়াদসহ।'), links: [{ to: '/lands', label: tx('জমির তালিকা') }] },
  '/lands/transfers': { title: tx('জমি হস্তান্তর'), phase: 9, about: tx('সব মালিকানা হস্তান্তরের তালিকা। হস্তান্তর নিজে জমির পাতা থেকে এখনই করা যায়।'), links: [{ to: '/lands', label: tx('জমির তালিকা') }] },
  '/lands/reports': { title: tx('জমির রিপোর্ট'), phase: 9, about: tx('মৌজা/ধরন/চাষের অবস্থা অনুযায়ী জমির সারসংক্ষেপ রিপোর্ট।'), links: [{ to: '/data-health', label: 'Data Health' }] },
  '/irrigation/lookup': { title: tx('মৌসুম / জমির ধরন অনুসন্ধান'), phase: 9, about: tx('কোন মৌসুমে কোন জমির ধরনে কত রেট — এক নজরে খোঁজা।'), links: [{ to: '/irrigation/rates', label: tx('সেচের রেট') }] },
  '/irrigation/category-rates': { title: tx('ক্যাটাগরিভিত্তিক রেট'), phase: 9, about: tx('সেচের ক্যাটাগরি × জমির ধরন রেট ম্যাট্রিক্স।'), links: [{ to: '/irrigation/rates', label: tx('সেচের রেট') }] },
  '/members/voter-history': { title: tx('ভোটার ইতিহাস'), phase: 9, about: tx('প্রতি নির্বাচনের ভোটার তালিকার সংরক্ষিত কপি।'), links: [{ to: '/members/voters', label: tx('ভোটার তালিকা') }] },
  '/members/voter-audit': { title: tx('ভোটার অডিট'), phase: 9, about: tx('ভোটার যোগ্যতা পরিবর্তনের ইতিহাস ও কারণ।'), links: [{ to: '/members/voters', label: tx('ভোটার তালিকা') }] },
  '/loans/guarantors': { title: tx('জামিনদার'), phase: 9, about: tx('সব জামিনদার ও তাদের দায়বদ্ধ ঋণের তালিকা।'), links: [{ to: '/loans', label: tx('ঋণের তালিকা') }] },
  '/cashbook/irrigation': { title: tx('সেচ নগদ বিবরণী'), phase: 9, about: tx('সেচ খাতের দৈনিক/মাসিক নগদ আয়-ব্যয়ের বিবরণী।'), links: [{ to: '/accounting/ledger', label: tx('ক্যাশ বই (খতিয়ান)') }] },
  '/cashbook/society': { title: tx('সমিতির নগদ বিবরণী'), phase: 9, about: tx('সমিতি খাতের দৈনিক/মাসিক নগদ আয়-ব্যয়ের বিবরণী।'), links: [{ to: '/accounting/ledger', label: tx('ক্যাশ বই (খতিয়ান)') }] },
  '/cashbook/income-expense': { title: tx('আয়-ব্যয় নগদ বই'), phase: 9, about: tx('খাতভিত্তিক আয় ও ব্যয়ের নগদ বই।'), links: [{ to: '/accounting/ledger', label: tx('ক্যাশ বই (খতিয়ান)') }] },
  '/audit/exports': { title: tx('Export অডিট'), phase: 9, about: tx('কে, কখন, কোন তালিকা Export/ডাউনলোড করেছে তার লগ।'), links: [{ to: '/audit/logs', label: tx('সিস্টেম অডিট লগ') }] },
  '/assets/reports': { title: tx('সম্পদের রিপোর্ট'), phase: 9, about: tx('সম্পদ রেজিস্টার, অবচয় সূচি ও বিক্রয়/বাতিলের রিপোর্ট (PDF/Excel)।'), links: [{ to: '/assets', label: tx('সম্পদ রেজিস্টার (CSV)') }] },
  '/accounting/summary': { title: tx('আর্থিক সারসংক্ষেপ'), phase: 9, about: tx('আয়-ব্যয় বিবরণী, স্থিতিপত্র ও খাতভিত্তিক সারসংক্ষেপ।'), links: [{ to: '/accounting/trial-balance', label: tx('রেওয়ামিল') }] },
  '/accounting/source-vs-ledger': { title: tx('উৎস বনাম খতিয়ান'), phase: 9, about: tx('প্রতিটি মডিউলের নিজস্ব হিসাব বনাম খতিয়ানের জের মিলিয়ে দেখা।'), links: [{ to: '/accounting/trial-balance', label: tx('রেওয়ামিল') }] },
  '/accounting/irrigation-cash-bank': { title: tx('সেচের নগদ ও ব্যাংক'), phase: 9, about: tx('সেচ খাতের নগদ ও ব্যাংক জের আলাদা করে।'), links: [{ to: '/accounting/funds', label: tx('হাতে নগদ') }] },
  '/accounting/ledger-integrity': { title: tx('লেজার সঠিকতা যাচাই'), phase: 9, about: tx('ডেবিট-ক্রেডিট সমতা, ভাঙা লিংক ও অসম্পূর্ণ ভাউচার স্বয়ংক্রিয়ভাবে খোঁজা।'), links: [{ to: '/accounting/trial-balance', label: tx('রেওয়ামিল') }] },
  '/accounting/public-payments': { title: tx('অনলাইন পেমেন্ট অনুরোধ'), phase: 9, about: tx('লগইন ছাড়া অনলাইনে পেমেন্টের অনুরোধ → যাচাই → রশিদ।') },
  '/accounting/payment-reconciliation': { title: tx('পেমেন্ট মিলকরণ'), phase: 9, about: tx('মডিউলের আদায় বনাম খতিয়ানের এন্ট্রি মিলিয়ে দেখা।'), links: [{ to: '/payments/receipts', label: tx('রশিদ তালিকা') }] },
  '/reports/collections': { title: tx('আদায়ের রিপোর্ট'), phase: 9, about: tx('দিন/মাস/মৌজা/খাত অনুযায়ী আদায়ের রিপোর্ট (PDF/Excel)।'), links: [{ to: '/payments/receipts', label: tx('রশিদ তালিকা') }] },
  '/reports/dues': { title: tx('বকেয়ার রিপোর্ট'), phase: 9, about: tx('সেচ, ঋণ ও অন্যান্য বকেয়ার একত্রিত রিপোর্ট।'), links: [{ to: '/irrigation/dues', label: tx('সেচের বকেয়া') }, { to: '/loans/dues', label: tx('ঋণের বকেয়া') }] },
  '/reports/audit': { title: tx('অডিট রিপোর্ট'), phase: 9, about: tx('নিরীক্ষকের জন্য বার্ষিক/মাসিক অডিট রিপোর্ট।'), links: [{ to: '/audit/logs', label: tx('সিস্টেম অডিট লগ') }] },
  '/audit/integrity-scan': { title: tx('ডেটা সঠিকতা স্ক্যান'), phase: 9, about: tx('সব মডিউলের তথ্যে অসঙ্গতি খোঁজার স্বয়ংক্রিয় স্ক্যান।'), links: [{ to: '/data-health', label: 'Data Health' }] },
  '/admin/receipt-serials': { title: tx('রশিদ সিরিয়াল প্রশাসন'), phase: 9, about: tx('রশিদ বই/সিরিয়াল বরাদ্দ ও ফাঁক পর্যবেক্ষণ।'), links: [{ to: '/settings/sequences', label: tx('সিরিয়াল নম্বর') }] },
  '/imports/savings-opening': { title: tx('সঞ্চয়ের প্রারম্ভিক ইমপোর্ট'), phase: 10, about: tx('পুরোনো খাতার সঞ্চয় জের একসাথে ইমপোর্ট।') },
  '/imports/share-opening': { title: tx('শেয়ারের প্রারম্ভিক ইমপোর্ট'), phase: 10, about: tx('পুরোনো খাতার শেয়ার জের একসাথে ইমপোর্ট।') },
  '/imports/loan-opening': { title: tx('ঋণের প্রারম্ভিক ইমপোর্ট'), phase: 10, about: tx('চলমান পুরোনো ঋণ ও বকেয়া একসাথে ইমপোর্ট।') },
  '/imports/payments': { title: tx('পেমেন্ট ইমপোর্ট'), phase: 10, about: tx('পুরোনো আদায়ের তথ্য একসাথে ইমপোর্ট।'), links: [{ to: '/payments/collect?legacy=1', label: tx('পুরোনো রশিদ এন্ট্রি') }] },
  '/imports/legacy-irrigation': { title: tx('পুরোনো সেচ ডেটা ইমপোর্ট'), phase: 10, about: tx('আগের মৌসুমের সেচ ইনভয়েস ও আদায় ইমপোর্ট।') },
  '/imports/audit': { title: tx('ইমপোর্ট অডিট'), phase: 10, about: tx('সব ইমপোর্টের ব্যাচ, ফলাফল ও বাদ পড়া সারি।'), links: [{ to: '/imports', label: tx('ইমপোর্টের ইতিহাস') }] },
  '/settings/branding': { title: tx('ব্র্যান্ডিং ও লোগো'), phase: 10, about: tx('লোগো, রং ও রশিদ/রিপোর্টের শিরোনাম আলাদা পাতায়।'), links: [{ to: '/settings/general', label: tx('সাধারণ সেটিংস (লোগো)') }] },
  '/settings/receipt': { title: tx('রশিদ সেটিংস'), phase: 10, about: tx('রশিদের নকশা, কপি সংখ্যা, পাদটীকা ও প্রিন্টার।'), links: [{ to: '/settings/general', label: tx('সাধারণ সেটিংস') }] },
  '/settings/sms': { title: tx('SMS সেটিংস'), phase: 9, about: tx('SMS গেটওয়ে ও কোন ঘটনায় SMS যাবে।') },
  '/settings/sms-templates': { title: tx('SMS টেমপ্লেট'), phase: 9, about: tx('আদায়, বকেয়া ও কিস্তির SMS-এর বাংলা/ইংরেজি টেমপ্লেট।') },
  '/settings/sms-logs': { title: tx('SMS লগ'), phase: 9, about: tx('পাঠানো সব SMS ও তাদের অবস্থা।') },
  '/settings/financial-year': { title: tx('অর্থবছর'), phase: 9, about: tx('অর্থবছর খোলা/বন্ধ ও বছর শেষের সমাপনী এন্ট্রি।'), links: [{ to: '/accounting/periods', label: tx('হিসাবকাল বন্ধ') }] },
  '/settings/preferences': { title: tx('সিস্টেম পছন্দসমূহ'), phase: 10, about: tx('তারিখ/অঙ্কের ধরন, ডিফল্ট ভাষা ও অন্যান্য পছন্দ।'), links: [{ to: '/settings/general', label: tx('সাধারণ সেটিংস') }] },
  '/settings/license': { title: tx('লাইসেন্স ও ইনস্টলেশন'), phase: 10, about: tx('লাইসেন্সের তথ্য, সংস্করণ ও আপডেট।') },
}
